- hosts: localhost
  gather_facts: False

  tasks:

    - name: Provision a set of instances
      ec2:
         region: us-east-2
         key_name: main_pub
         group: launch-wizard-1
         instance_type: t2.micro
         image: "ami-0d5d9d301c853a04a"
         wait: true
         exact_count: 1
         count_tag:
            Name: "{{ vmID }}"
         instance_tags:
            Name:  "{{ vmID }}"
         
      register: ec2
    
    - name: install python module
      command: python3 -m pip install requests        


    - name: copy task python script
      copy:
        src: /root/grid-cloud/server/core/task.py
        dest: ~/task.py
        mode: 0644 

 

#- hosts: ec2hosts
#  name: configuration play
#  user: ec2-user
#  gather_facts: true
#
#  tasks:
#
#     - name: Check NTP service
#       service: name=ntpd state=started
