- hosts: localhost
  gather_facts: False

  tasks:

    - name: Launch instance
      ec2_instance:
         region: us-east-2
         key_name: main_pub
         instance_type: t2.micro
         image: "ami-0d5d9d301c853a04a"
         wait: true
         tags:
          Name: "{{ vmID }}"
        
         
      register: ec2
    
    - name: Install requests module to python3
      command: python3 -m pip install requests        


    - name: Copy task
      copy:
        src: /root/grid-cloud/server/core/task.py
        dest: ~/task.py
        mode: 0644 
    
    
    - name: Run task 
      command: "python3 ~/task.py {{ id }} {{ arg }} {{ addr }}"


 

#- hosts: ec2hosts
#  name: configuration play
#  user: ec2-user
#  gather_facts: true
#
#  tasks:
#
#     - name: Check NTP service
#       service: name=ntpd state=started
