- hosts: localhost
  gather_facts: False

  tasks:

    - name: Provision a set of instances
      ec2:
         region: us-east-2
         key_name: main_pub
         group: launch-wizard-1
         instance_type: t2.micro
         image: "ami-0d5d9d301c853a04a"
         wait: true
         exact_count: 1
         count_tag:
            Name: Demo
         instance_tags:
            Name: Demo
         
      register: ec2
    
    - name: Add all instance public IPs to host group
      add_host: hostname={{ item.public_ip }} groups=ec2hosts
      loop: "{{ ec2.instances }}"
    
    - name: install python module
      command: python3 -m pip install requests
    
    - name: create task dir
      command: mkdir /home/ubuntu/

    - name: copy task python script
      copy:
        src: /root/grid-cloud/server/core/task.py
        dest: /home/ubuntu/task.py
        owner: root
        mode: 7777 

 

#- hosts: ec2hosts
#  name: configuration play
#  user: ec2-user
#  gather_facts: true
#
#  tasks:
#
#     - name: Check NTP service
#       service: name=ntpd state=started
