- name: Terminate instances
  hosts: localhost
  tasks:
    - name: get ec2 instance id by its name tag
      ec2_instance:
         region: us-east-2
         filters:
            tag:Name: "{{ vmID }}"
      register: ec2
    
    - name: Wait 600 seconds for target connection to become reachable/usable
      wait_for_connection:


    
    - name: Terminate instances that were previously launched
      ec2:
        state: 'absent'
        region: us-east-2
        instance_ids: '{{ item.instance_id}}'
      with_items: "{{ec2.instances}}"
